import { Bellefair } from 'next/font/google'

import { Header } from '@/components'

import type { Metadata } from 'next'

const bellefair = Bellefair({ weight: ['400'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={bellefair.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
